[2023-05-01T15:18:31.285+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_from_gcs_to_bq_task manual__2023-05-01T15:18:30.287799+00:00 [queued]>
[2023-05-01T15:18:31.291+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_from_gcs_to_bq_task manual__2023-05-01T15:18:30.287799+00:00 [queued]>
[2023-05-01T15:18:31.291+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T15:18:31.292+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T15:18:31.292+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T15:18:31.306+0000] {taskinstance.py:1309} INFO - Executing <Task(GCSToBigQueryOperator): space_missions_launches_from_gcs_to_bq_task> on 2023-05-01 15:18:30.287799+00:00
[2023-05-01T15:18:31.312+0000] {standard_task_runner.py:55} INFO - Started process 13156 to run task
[2023-05-01T15:18:31.314+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'space_missions_launches_to_gcp_dag', 'space_missions_launches_from_gcs_to_bq_task', 'manual__2023-05-01T15:18:30.287799+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/space_missions_launches_to_gcp.py', '--cfg-path', '/tmp/tmpdo_g6k4p']
[2023-05-01T15:18:31.315+0000] {standard_task_runner.py:83} INFO - Job 78: Subtask space_missions_launches_from_gcs_to_bq_task
[2023-05-01T15:18:31.357+0000] {task_command.py:389} INFO - Running <TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_from_gcs_to_bq_task manual__2023-05-01T15:18:30.287799+00:00 [running]> on host e47d5c97588c
[2023-05-01T15:18:31.403+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=viktoria.k
AIRFLOW_CTX_DAG_ID=space_missions_launches_to_gcp_dag
AIRFLOW_CTX_TASK_ID=space_missions_launches_from_gcs_to_bq_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T15:18:30.287799+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-01T15:18:30.287799+00:00
[2023-05-01T15:18:31.411+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-05-01T15:18:31.415+0000] {gcs_to_bigquery.py:382} INFO - Using existing BigQuery table for storing data...
[2023-05-01T15:18:31.448+0000] {gcs_to_bigquery.py:636} INFO - Adding experimental 'schemaUpdateOptions': ['ALLOW_FIELD_ADDITION', 'ALLOW_FIELD_RELAXATION']
[2023-05-01T15:18:31.448+0000] {gcs_to_bigquery.py:386} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'de-camp-v1', 'datasetId': 'space_mission_launches', 'tableId': 'mission_launches'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://de-camp-v1_dl/mission_launches_2023-05-01.csv'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'schemaUpdateOptions': ['ALLOW_FIELD_ADDITION', 'ALLOW_FIELD_RELAXATION'], 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-05-01T15:18:31.449+0000] {bigquery.py:1546} INFO - Inserting job ***_space_missions_launches_to_gcp_dag_space_missions_launches_from_gcs_to_bq_task_2023_05_01T15_18_30_287799_00_00_00f5fa59c5c9a9d82179621d9f9e8b2d
[2023-05-01T15:18:32.294+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 445, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://de-camp-v1_dl/mission_launches_2023-05-01.csv
[2023-05-01T15:18:32.300+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=space_missions_launches_to_gcp_dag, task_id=space_missions_launches_from_gcs_to_bq_task, execution_date=20230501T151830, start_date=20230501T151831, end_date=20230501T151832
[2023-05-01T15:18:32.318+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 78 for task space_missions_launches_from_gcs_to_bq_task (404 Not found: URI gs://de-camp-v1_dl/mission_launches_2023-05-01.csv; 13156)
[2023-05-01T15:18:32.329+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-01T15:18:32.340+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
