[2023-05-01T16:54:55.161+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T16:54:53.736015+00:00 [queued]>
[2023-05-01T16:54:55.166+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T16:54:53.736015+00:00 [queued]>
[2023-05-01T16:54:55.167+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T16:54:55.167+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T16:54:55.167+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T16:54:55.176+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): space_missions_launches_to_gcp_task> on 2023-05-01 16:54:53.736015+00:00
[2023-05-01T16:54:55.181+0000] {standard_task_runner.py:55} INFO - Started process 17685 to run task
[2023-05-01T16:54:55.183+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'space_missions_launches_to_gcp_dag', 'space_missions_launches_to_gcp_task', 'manual__2023-05-01T16:54:53.736015+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/space_missions_launches_to_gcp.py', '--cfg-path', '/tmp/tmpbw13daae']
[2023-05-01T16:54:55.183+0000] {standard_task_runner.py:83} INFO - Job 117: Subtask space_missions_launches_to_gcp_task
[2023-05-01T16:54:55.221+0000] {task_command.py:389} INFO - Running <TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T16:54:53.736015+00:00 [running]> on host e47d5c97588c
[2023-05-01T16:54:55.263+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=viktoria.k
AIRFLOW_CTX_DAG_ID=space_missions_launches_to_gcp_dag
AIRFLOW_CTX_TASK_ID=space_missions_launches_to_gcp_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T16:54:53.736015+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-01T16:54:53.736015+00:00
[2023-05-01T16:54:55.269+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-05-01T16:54:56.204+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/space_missions_launches_to_gcp.py", line 40, in mission_launches_to_gcp
    existed_rows = pd.concat(existed_rows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2023-05-01T16:54:56.247+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=space_missions_launches_to_gcp_dag, task_id=space_missions_launches_to_gcp_task, execution_date=20230501T165453, start_date=20230501T165455, end_date=20230501T165456
[2023-05-01T16:54:56.266+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 117 for task space_missions_launches_to_gcp_task (No objects to concatenate; 17685)
[2023-05-01T16:54:56.278+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-01T16:54:56.294+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
