[2023-05-01T13:36:54.179+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T11:30:38.175260+00:00 [queued]>
[2023-05-01T13:36:54.184+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T11:30:38.175260+00:00 [queued]>
[2023-05-01T13:36:54.184+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T13:36:54.184+0000] {taskinstance.py:1289} INFO - Starting attempt 15 of 15
[2023-05-01T13:36:54.184+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T13:36:54.196+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): space_missions_launches_to_gcp_task> on 2023-05-01 11:30:38.175260+00:00
[2023-05-01T13:36:54.200+0000] {standard_task_runner.py:55} INFO - Started process 8393 to run task
[2023-05-01T13:36:54.202+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'space_missions_launches_to_gcp_dag', 'space_missions_launches_to_gcp_task', 'manual__2023-05-01T11:30:38.175260+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/space_missions_launches_to_gcp.py', '--cfg-path', '/tmp/tmp2g2141y0']
[2023-05-01T13:36:54.203+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask space_missions_launches_to_gcp_task
[2023-05-01T13:36:54.240+0000] {task_command.py:389} INFO - Running <TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T11:30:38.175260+00:00 [running]> on host e47d5c97588c
[2023-05-01T13:36:54.290+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=viktoria.k
AIRFLOW_CTX_DAG_ID=space_missions_launches_to_gcp_dag
AIRFLOW_CTX_TASK_ID=space_missions_launches_to_gcp_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T11:30:38.175260+00:00
AIRFLOW_CTX_TRY_NUMBER=15
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-01T11:30:38.175260+00:00
[2023-05-01T13:36:54.296+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-05-01T13:36:55.183+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/space_missions_launches_to_gcp.py", line 32, in mission_launches_to_gcp
    temp.write(mission_launches.to_csv())
  File "/usr/local/lib/python3.7/tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
[2023-05-01T13:36:55.189+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=space_missions_launches_to_gcp_dag, task_id=space_missions_launches_to_gcp_task, execution_date=20230501T113038, start_date=20230501T133654, end_date=20230501T133655
[2023-05-01T13:36:55.210+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 29 for task space_missions_launches_to_gcp_task (a bytes-like object is required, not 'str'; 8393)
[2023-05-01T13:36:55.256+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-01T13:36:55.268+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
