[2023-05-01T16:19:42.174+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T16:19:08.575322+00:00 [queued]>
[2023-05-01T16:19:42.178+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T16:19:08.575322+00:00 [queued]>
[2023-05-01T16:19:42.178+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T16:19:42.178+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2023-05-01T16:19:42.178+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T16:19:42.187+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): space_missions_launches_to_gcp_task> on 2023-05-01 16:19:08.575322+00:00
[2023-05-01T16:19:42.192+0000] {standard_task_runner.py:55} INFO - Started process 16040 to run task
[2023-05-01T16:19:42.194+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'space_missions_launches_to_gcp_dag', 'space_missions_launches_to_gcp_task', 'manual__2023-05-01T16:19:08.575322+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/space_missions_launches_to_gcp.py', '--cfg-path', '/tmp/tmpcc3a0y8t']
[2023-05-01T16:19:42.194+0000] {standard_task_runner.py:83} INFO - Job 110: Subtask space_missions_launches_to_gcp_task
[2023-05-01T16:19:42.229+0000] {task_command.py:389} INFO - Running <TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T16:19:08.575322+00:00 [running]> on host e47d5c97588c
[2023-05-01T16:19:42.268+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=viktoria.k
AIRFLOW_CTX_DAG_ID=space_missions_launches_to_gcp_dag
AIRFLOW_CTX_TASK_ID=space_missions_launches_to_gcp_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T16:19:08.575322+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-01T16:19:08.575322+00:00
[2023-05-01T16:19:42.273+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-05-01T16:19:43.057+0000] {space_missions_launches_to_gcp.py:39} WARNING - !!!!!!!!!!['mission_launches_2023-05-01.csv']
[2023-05-01T16:19:43.744+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/space_missions_launches_to_gcp.py", line 43, in mission_launches_to_gcp
    existed_rows=pd.concat([existed_rows,mission_launches]).drop_duplicates(keep=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 384, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid
[2023-05-01T16:19:43.749+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=space_missions_launches_to_gcp_dag, task_id=space_missions_launches_to_gcp_task, execution_date=20230501T161908, start_date=20230501T161942, end_date=20230501T161943
[2023-05-01T16:19:43.758+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 110 for task space_missions_launches_to_gcp_task (cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid; 16040)
[2023-05-01T16:19:43.770+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-01T16:19:43.786+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
