[2023-05-01T15:05:35.470+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T15:05:33.917535+00:00 [queued]>
[2023-05-01T15:05:35.475+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T15:05:33.917535+00:00 [queued]>
[2023-05-01T15:05:35.475+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T15:05:35.475+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T15:05:35.475+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T15:05:35.484+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): space_missions_launches_to_gcp_task> on 2023-05-01 15:05:33.917535+00:00
[2023-05-01T15:05:35.489+0000] {standard_task_runner.py:55} INFO - Started process 12558 to run task
[2023-05-01T15:05:35.491+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'space_missions_launches_to_gcp_dag', 'space_missions_launches_to_gcp_task', 'manual__2023-05-01T15:05:33.917535+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/space_missions_launches_to_gcp.py', '--cfg-path', '/tmp/tmphza5n45a']
[2023-05-01T15:05:35.491+0000] {standard_task_runner.py:83} INFO - Job 72: Subtask space_missions_launches_to_gcp_task
[2023-05-01T15:05:35.526+0000] {task_command.py:389} INFO - Running <TaskInstance: space_missions_launches_to_gcp_dag.space_missions_launches_to_gcp_task manual__2023-05-01T15:05:33.917535+00:00 [running]> on host e47d5c97588c
[2023-05-01T15:05:35.565+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=viktoria.k
AIRFLOW_CTX_DAG_ID=space_missions_launches_to_gcp_dag
AIRFLOW_CTX_TASK_ID=space_missions_launches_to_gcp_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T15:05:33.917535+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-01T15:05:33.917535+00:00
[2023-05-01T15:05:35.570+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-05-01T15:05:36.593+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/space_missions_launches_to_gcp.py", line 42, in mission_launches_to_gcp
    if not mission_launches.empty():
TypeError: 'bool' object is not callable
[2023-05-01T15:05:36.598+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=space_missions_launches_to_gcp_dag, task_id=space_missions_launches_to_gcp_task, execution_date=20230501T150533, start_date=20230501T150535, end_date=20230501T150536
[2023-05-01T15:05:36.606+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 72 for task space_missions_launches_to_gcp_task ('bool' object is not callable; 12558)
[2023-05-01T15:05:36.626+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-01T15:05:36.645+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
